### ISSUE TITLE
Dev: reuse GitHub Action workflows

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/CodeIgniter4#7819]
### TODO

- [x] create [codeigniter4/.github](https://github.com/codeigniter4/.github) repository
- [x] add workflows in `codeigniter4/.github` based on `shield`
    - https://github.com/codeigniter4/.github/pull/1
    - https://github.com/codeigniter4/.github/pull/2 
    - https://github.com/codeigniter4/.github/pull/3
      - https://github.com/codeigniter4/.github/pull/5
      - https://github.com/codeigniter4/.github/pull/6
    - https://github.com/codeigniter4/.github/pull/4
    - https://github.com/codeigniter4/.github/pull/15
- [x] reuse workflows
   - [x] shield
     - https://github.com/codeigniter4/shield/pull/811
     - https://github.com/codeigniter4/shield/pull/813
     - https://github.com/codeigniter4/shield/pull/863
   - [x] tasks
     - https://github.com/codeigniter4/tasks/pull/128
   - [x] settings
     - https://github.com/codeigniter4/settings/pull/95
     - https://github.com/codeigniter4/settings/pull/102
   - [x] cache
     - https://github.com/codeigniter4/cache/pull/16
     - https://github.com/codeigniter4/cache/pull/20
   - [x] website
     - https://github.com/codeigniter4projects/website/pull/399 
- [x] https://github.com/codeigniter4/.github/issues/14

### References

- https://docs.github.com/en/actions/using-workflows/reusing-workflows
